name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.x
    - name: Cross build
      run: make cross
    - name: Upload
      run: make upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
